import 'package:flutter/material.dart';
import '../models/emergency_protocol.dart';

final Map<String, EmergencyProtocol> mockEmergencyData = {
  'heart': EmergencyProtocol(
    id: 'heart',
    icon: '❤️',
    title: 'Heart Attack',
    color: const Color.fromRGBO(21, 101, 192, 0.15),
    callLabel: 'Call Ambulance',
    panicLabel: '● Cardiac emergency detected',
    initialMsg: 'Victim is having a heart attack',
    responses: const [
      EmergencyResponse(text: '🫀 Possible cardiac arrest — acting immediately', styleClass: 'urg'),
      EmergencyResponse(text: '📞 Calling 112 — ambulance dispatched', styleClass: 'urg'),
      EmergencyResponse(text: '💊 Chew an aspirin if available and conscious', styleClass: 'wrn'),
      EmergencyResponse(text: '🛌 Lay him flat, loosen shirt around chest', styleClass: 'wrn'),
      EmergencyResponse(text: '💪 Begin CPR — 30 hard compressions, then 2 breaths', styleClass: 'wrn'),
    ],
    timelineDesc: 'Cardiac event — person collapsed',
    timelineGuidance: 'CPR guidance started',
    cardTitle: 'Cardiac Protocol',
    cardSub: 'Heart attack response',
    cards: const [
      EmergencyActionCard(icon: '💪', label: 'Start CPR', borderColor: Color.fromRGBO(229, 57, 53, 0.3), bgColor: Color.fromRGBO(229, 57, 53, 0.15)),
      EmergencyActionCard(icon: '🛌', label: 'Lay Flat', borderColor: Color.fromRGBO(255, 143, 0, 0.3), bgColor: Color.fromRGBO(255, 143, 0, 0.15)),
      EmergencyActionCard(icon: '💊', label: 'Give Aspirin', borderColor: Color.fromRGBO(21, 101, 192, 0.3), bgColor: Color.fromRGBO(21, 101, 192, 0.15)),
      EmergencyActionCard(icon: '😮‍💨', label: 'Stay Calm', borderColor: Color.fromRGBO(46, 125, 50, 0.3), bgColor: Color.fromRGBO(46, 125, 50, 0.15)),
    ],
    voiceSteps: const [
      'Stay calm. Help is on the way.',
      'Lay him flat on a firm surface.',
      'Tilt head back, check for breathing.',
      'Place both hands on center of chest.',
      'Push hard 30 times, then 2 breaths.',
      'Keep going — ambulance is 4 minutes away.'
    ],
  ),
  'breathing': EmergencyProtocol(
    id: 'breathing',
    icon: '😮‍💨',
    title: 'Breathing Issue',
    color: const Color.fromRGBO(255, 143, 0, 0.15),
    callLabel: 'Call Ambulance',
    panicLabel: '● Breathing emergency detected',
    initialMsg: 'Victim is choking and cannot breathe',
    responses: const [
      EmergencyResponse(text: '😮‍💨 Breathing emergency — responding now', styleClass: 'urg'),
      EmergencyResponse(text: '📞 Call 112 immediately', styleClass: 'urg'),
      EmergencyResponse(text: '🤲 If choking: stand behind, give 5 firm back blows between shoulder blades', styleClass: 'wrn'),
      EmergencyResponse(text: '👊 If back blows fail: give 5 abdominal thrusts (Heimlich maneuver)', styleClass: 'wrn'),
      EmergencyResponse(text: '🫁 If unconscious and not breathing: begin rescue breaths', styleClass: 'wrn'),
    ],
    timelineDesc: 'Breathing emergency — choking reported',
    timelineGuidance: 'Breathing guidance started',
    cardTitle: 'Breathing Protocol',
    cardSub: 'Choking / airway emergency',
    cards: const [
      EmergencyActionCard(icon: '🤲', label: 'Back Blows', borderColor: Color.fromRGBO(255, 143, 0, 0.3), bgColor: Color.fromRGBO(255, 143, 0, 0.15)),
      EmergencyActionCard(icon: '👊', label: 'Heimlich', borderColor: Color.fromRGBO(229, 57, 53, 0.3), bgColor: Color.fromRGBO(229, 57, 53, 0.15)),
      EmergencyActionCard(icon: '🫁', label: 'Rescue Breaths', borderColor: Color.fromRGBO(21, 101, 192, 0.3), bgColor: Color.fromRGBO(21, 101, 192, 0.15)),
      EmergencyActionCard(icon: '😮‍💨', label: 'Stay Calm', borderColor: Color.fromRGBO(46, 125, 50, 0.3), bgColor: Color.fromRGBO(46, 125, 50, 0.15)),
    ],
    voiceSteps: const [
      'Is the person conscious? Can they speak?',
      'If choking: lean them forward slightly.',
      'Give 5 firm blows between shoulder blades.',
      'If no change: wrap arms around their waist.',
      'Thrust upward firmly just below the ribs.',
      'If they collapse: begin CPR and rescue breaths.'
    ],
  ),
  'asthma': EmergencyProtocol(

    id: 'asthma',
    icon: '🫁',
    title: 'Asthma Attack',
    color: const Color.fromRGBO(21, 101, 192, 0.15),
    callLabel: 'Call Ambulance',
    panicLabel: '● Asthma emergency detected',
    initialMsg: 'Victim is having a severe asthma attack',
    responses: const [
      EmergencyResponse(text: '🫁 Asthma attack detected — stay calm and breathe with me', styleClass: 'urg'),
      EmergencyResponse(text: '📞 If no inhaler or worsening: Call 112 immediately', styleClass: 'urg'),
      EmergencyResponse(text: '🧘 Sit the person upright — do NOT let them lie down', styleClass: 'wrn'),
      EmergencyResponse(text: '💨 Help them use their blue (reliever) inhaler — 1 puff every 30-60 seconds', styleClass: 'wrn'),
      EmergencyResponse(text: '😮‍💨 Encourage slow, steady breaths while waiting for help', styleClass: 'inf'),
    ],
    timelineDesc: 'Asthma attack — inhaler protocol started',
    timelineGuidance: 'Respiratory support guidance started',
    cardTitle: 'Asthma Protocol',
    cardSub: 'Inhaler / breathing response',
    cards: const [
      EmergencyActionCard(icon: '🧘', label: 'Sit Upright', borderColor: Color.fromRGBO(21, 101, 192, 0.3), bgColor: Color.fromRGBO(21, 101, 192, 0.15)),
      EmergencyActionCard(icon: '💨', label: 'Use Inhaler', borderColor: Color.fromRGBO(46, 125, 50, 0.3), bgColor: Color.fromRGBO(46, 125, 50, 0.15)),
      EmergencyActionCard(icon: '📞', label: 'Call 112', borderColor: Color.fromRGBO(229, 57, 53, 0.3), bgColor: Color.fromRGBO(229, 57, 53, 0.15)),
      EmergencyActionCard(icon: '😮‍💨', label: 'Slow Breath', borderColor: Color.fromRGBO(255, 143, 0, 0.3), bgColor: Color.fromRGBO(255, 143, 0, 0.15)),
    ],
    voiceSteps: const [
      'Sit up straight. Do not lie down.',
      'Take one puff of your reliever inhaler.',
      'Breathe in slowly and out slowly.',
      'If you feel worse, use the inhaler again.',
      'Help is on the way. Keep sitting up.',
      'Try to stay as calm as possible.'
    ],
  ),
  'bleeding': EmergencyProtocol(
    id: 'bleeding',
    icon: '🩸',
    title: 'Severe Bleeding',
    color: const Color.fromRGBO(183, 28, 28, 0.15),
    callLabel: 'Call Ambulance',
    panicLabel: '● Severe bleeding detected',
    initialMsg: 'Victim has a deep cut and is bleeding heavily',
    responses: const [
      EmergencyResponse(text: '🩸 Severe bleeding detected — act immediately', styleClass: 'urg'),
      EmergencyResponse(text: '📞 Call 112 — request ambulance', styleClass: 'urg'),
      EmergencyResponse(text: '🤲 Apply firm, continuous pressure to the wound — do NOT release', styleClass: 'wrn'),
      EmergencyResponse(text: '🧣 Use a cloth, shirt or bandage — elevate the limb above heart level', styleClass: 'wrn'),
      EmergencyResponse(text: '🚫 Do NOT remove the cloth if it soaks through — add more on top', styleClass: 'urg'),
    ],
    timelineDesc: 'Severe bleeding — deep wound reported',
    timelineGuidance: 'Bleeding control guidance started',
    cardTitle: 'Bleeding Protocol',
    cardSub: 'Wound / haemorrhage control',
    cards: const [
      EmergencyActionCard(icon: '🤲', label: 'Apply Pressure', borderColor: Color.fromRGBO(229, 57, 53, 0.3), bgColor: Color.fromRGBO(229, 57, 53, 0.15)),
      EmergencyActionCard(icon: '⬆️', label: 'Elevate Limb', borderColor: Color.fromRGBO(255, 143, 0, 0.3), bgColor: Color.fromRGBO(255, 143, 0, 0.15)),
      EmergencyActionCard(icon: '🧣', label: 'Bandage Tight', borderColor: Color.fromRGBO(21, 101, 192, 0.3), bgColor: Color.fromRGBO(21, 101, 192, 0.15)),
      EmergencyActionCard(icon: '🚫', label: 'Don\'t Release', borderColor: Color.fromRGBO(183, 28, 28, 0.3), bgColor: Color.fromRGBO(183, 28, 28, 0.15)),
    ],
    voiceSteps: const [
      'Press hard on the wound right now.',
      'Use any cloth or clothing you have.',
      'Keep pressing — do not let go.',
      'Raise the injured limb above their heart.',
      'If it soaks through, add more cloth on top.',
      'Ambulance is coming — keep the pressure on.'
    ],
  ),
  'unconscious': EmergencyProtocol(
    id: 'unconscious',
    icon: '🫥',
    title: 'Unconscious Person',
    color: const Color.fromRGBO(21, 101, 192, 0.15),
    callLabel: 'Call Ambulance',
    panicLabel: '● Unresponsive person detected',
    initialMsg: 'Victim collapsed and is not responding to me',
    responses: const [
      EmergencyResponse(text: '🫥 Unresponsive person — checking vitals protocol', styleClass: 'urg'),
      EmergencyResponse(text: '📞 Call 112 immediately', styleClass: 'urg'),
      EmergencyResponse(text: '👂 Shout their name, tap shoulders — check response', styleClass: 'wrn'),
      EmergencyResponse(text: '🫁 Tilt head back, lift chin, look for chest movement', styleClass: 'wrn'),
      EmergencyResponse(text: '💪 No breathing detected — start CPR: 30 compressions, 2 breaths', styleClass: 'urg'),
      EmergencyResponse(text: '🔄 If breathing: place in recovery position on their side', styleClass: 'inf'),
    ],
    timelineDesc: 'Unconscious person — unresponsive',
    timelineGuidance: 'Resuscitation guidance started',
    cardTitle: 'Unconscious Protocol',
    cardSub: 'Unresponsive / collapsed person',
    cards: const [
      EmergencyActionCard(icon: '👂', label: 'Check Response', borderColor: Color.fromRGBO(255, 143, 0, 0.3), bgColor: Color.fromRGBO(255, 143, 0, 0.15)),
      EmergencyActionCard(icon: '🫁', label: 'Check Breathing', borderColor: Color.fromRGBO(21, 101, 192, 0.3), bgColor: Color.fromRGBO(21, 101, 192, 0.15)),
      EmergencyActionCard(icon: '💪', label: 'Start CPR', borderColor: Color.fromRGBO(229, 57, 53, 0.3), bgColor: Color.fromRGBO(229, 57, 53, 0.15)),
      EmergencyActionCard(icon: '🔄', label: 'Recovery Position', borderColor: Color.fromRGBO(46, 125, 50, 0.3), bgColor: Color.fromRGBO(46, 125, 50, 0.15)),
    ],
    voiceSteps: const [
      'Tap shoulders and shout their name.',
      'No response — check for breathing.',
      'Tilt head back and lift the chin.',
      'No breathing: place hands on chest center.',
      '30 hard compressions, then 2 breaths.',
      'If breathing returns: roll to recovery position.'
    ],
  ),
  'accident': EmergencyProtocol(
    id: 'accident',
    icon: '🚗',
    title: 'Road Accident',
    color: const Color.fromRGBO(229, 57, 53, 0.15),
    callLabel: 'Call Ambulance + Police',
    panicLabel: '● Road accident detected',
    initialMsg: 'Victim was in a road accident and is injured',
    responses: const [
      EmergencyResponse(text: '🚗 Road accident detected', styleClass: 'urg'),
      EmergencyResponse(text: '📞 Call 112 (ambulance) and 100 (police)', styleClass: 'urg'),
      EmergencyResponse(text: '🚫 Do NOT move the injured person — risk of spinal injury', styleClass: 'wrn'),
      EmergencyResponse(text: '🩸 Apply firm pressure on any bleeding wounds', styleClass: 'wrn'),
      EmergencyResponse(text: '⚠️ Turn on vehicle hazard lights to warn other drivers', styleClass: 'inf'),
      EmergencyResponse(text: '🧥 Keep injured person warm using a jacket', styleClass: 'inf'),
    ],
    timelineDesc: 'Road accident — injury reported',
    timelineGuidance: 'First-aid guidance started',
    cardTitle: 'Accident Protocol',
    cardSub: 'Road crash response',
    cards: const [
      EmergencyActionCard(icon: '🛑', label: 'Don\'t Move', borderColor: Color.fromRGBO(229, 57, 53, 0.3), bgColor: Color.fromRGBO(229, 57, 53, 0.15)),
      EmergencyActionCard(icon: '🩸', label: 'Stop Bleeding', borderColor: Color.fromRGBO(183, 28, 28, 0.3), bgColor: Color.fromRGBO(183, 28, 28, 0.15)),
      EmergencyActionCard(icon: '⚠️', label: 'Warn Traffic', borderColor: Color.fromRGBO(255, 193, 7, 0.3), bgColor: Color.fromRGBO(255, 193, 7, 0.15)),
      EmergencyActionCard(icon: '😮‍💨', label: 'Stay Calm', borderColor: Color.fromRGBO(21, 101, 192, 0.3), bgColor: Color.fromRGBO(21, 101, 192, 0.15)),
    ],
    voiceSteps: const [
      'Is the person conscious? Call out to them.',
      'Do not move them — risk of spine injury.',
      'Apply pressure to any bleeding wound now.',
      'Turn on vehicle hazard lights.',
      'Keep them warm and still until help arrives.',
      'Ambulance and police are on the way.'
    ],
  ),
  'fire': EmergencyProtocol(
    id: 'fire',
    icon: '🔥',
    title: 'Fire Emergency',
    color: const Color.fromRGBO(255, 143, 0, 0.15),
    callLabel: 'Call Fire Brigade',
    panicLabel: '● Fire emergency detected',
    initialMsg: 'There is a fire in our building and someone is trapped',
    responses: const [
      EmergencyResponse(text: '🔥 Fire emergency — life at immediate risk', styleClass: 'urg'),
      EmergencyResponse(text: '📞 Call 101 (fire brigade) and 112 now', styleClass: 'urg'),
      EmergencyResponse(text: '🚪 Evacuate immediately — use stairs only, never the lift', styleClass: 'wrn'),
      EmergencyResponse(text: '⬇️ Stay low and crawl — air is cleaner near the floor', styleClass: 'wrn'),
      EmergencyResponse(text: '🖐️ Feel doors before opening — hot door means fire behind it', styleClass: 'wrn'),
      EmergencyResponse(text: '🚫 Once outside: do NOT re-enter the building', styleClass: 'urg'),
    ],
    timelineDesc: 'Fire reported — person trapped',
    timelineGuidance: 'Evacuation guidance started',
    cardTitle: 'Fire Protocol',
    cardSub: 'Building fire response',
    cards: const [
      EmergencyActionCard(icon: '🚪', label: 'Evacuate Now', borderColor: Color.fromRGBO(255, 143, 0, 0.3), bgColor: Color.fromRGBO(255, 143, 0, 0.15)),
      EmergencyActionCard(icon: '⬇️', label: 'Stay Low', borderColor: Color.fromRGBO(229, 57, 53, 0.3), bgColor: Color.fromRGBO(229, 57, 53, 0.15)),
      EmergencyActionCard(icon: '🚫', label: 'No Elevator', borderColor: Color.fromRGBO(183, 28, 28, 0.3), bgColor: Color.fromRGBO(183, 28, 28, 0.15)),
      EmergencyActionCard(icon: '😮‍💨', label: 'Cover Mouth', borderColor: Color.fromRGBO(21, 101, 192, 0.3), bgColor: Color.fromRGBO(21, 101, 192, 0.15)),
    ],
    voiceSteps: const [
      'Get out now. Leave everything behind.',
      'Feel the door — hot door means danger.',
      'Stay low and crawl under the smoke.',
      'Use only the stairs — never the lift.',
      'Once outside move far from the building.',
      'Do not go back in. Fire brigade is coming.'
    ],
  ),
  'crime': EmergencyProtocol(
    id: 'crime',
    icon: '🚨',
    title: 'Crime / Threat',
    color: const Color.fromRGBO(46, 125, 50, 0.15),
    callLabel: 'Call Police',
    panicLabel: '● Threat situation detected',
    initialMsg: 'Victim is being attacked and robbed',
    responses: const [
      EmergencyResponse(text: '🚨 Threat situation — taking immediate action', styleClass: 'urg'),
      EmergencyResponse(text: '📞 Call 100 (police) — stay on the line', styleClass: 'urg'),
      EmergencyResponse(text: '🏃 If safe: move away quickly from the threat', styleClass: 'wrn'),
      EmergencyResponse(text: '📍 Note your exact location — street name, landmark', styleClass: 'inf'),
      EmergencyResponse(text: '🔇 If hiding: silence your phone and stay completely still', styleClass: 'suc'),
      EmergencyResponse(text: '🚫 Do NOT confront or challenge the attacker', styleClass: 'wrn'),
    ],
    timelineDesc: 'Crime / threat — active situation',
    timelineGuidance: 'Safety guidance started',
    cardTitle: 'Safety Protocol',
    cardSub: 'Crime / threat response',
    cards: const [
      EmergencyActionCard(icon: '🏃', label: 'Move Away', borderColor: Color.fromRGBO(229, 57, 53, 0.3), bgColor: Color.fromRGBO(229, 57, 53, 0.15)),
      EmergencyActionCard(icon: '📍', label: 'Note Location', borderColor: Color.fromRGBO(21, 101, 192, 0.3), bgColor: Color.fromRGBO(21, 101, 192, 0.15)),
      EmergencyActionCard(icon: '🔇', label: 'Stay Silent', borderColor: Color.fromRGBO(255, 143, 0, 0.3), bgColor: Color.fromRGBO(255, 143, 0, 0.15)),
      EmergencyActionCard(icon: '😮‍💨', label: 'Stay Calm', borderColor: Color.fromRGBO(46, 125, 50, 0.3), bgColor: Color.fromRGBO(46, 125, 50, 0.15)),
    ],
    voiceSteps: const [
      'Are you in immediate danger right now?',
      'Move to a safe location if possible.',
      'Lock or barricade a door if you are hiding.',
      'Note any landmarks — police need your position.',
      'Do not challenge the attacker.',
      'Police are on the way. Stay hidden and quiet.'
    ],
  ),
  'poisoning': EmergencyProtocol(
    id: 'poisoning',
    icon: '🧪',
    title: 'Poisoning / Overdose',
    color: const Color.fromRGBO(121, 85, 72, 0.15),
    callLabel: 'Call Poison Control',
    panicLabel: '● Toxic substance detected',
    initialMsg: 'Victim has swallowed poison',
    responses: const [
      EmergencyResponse(text: '🧪 Poisoning detected — acting immediately', styleClass: 'urg'),
      EmergencyResponse(text: '📞 Call 112 (Ambulance) or Poison Control now', styleClass: 'urg'),
      EmergencyResponse(text: '🚫 Do NOT induce vomiting unless instructed by a professional', styleClass: 'wrn'),
      EmergencyResponse(text: '🥛 Do NOT give the person anything to drink or eat', styleClass: 'wrn'),
      EmergencyResponse(text: '📦 Locate the container of the substance for identification', styleClass: 'inf'),
    ],
    timelineDesc: 'Toxic exposure — substance reported',
    timelineGuidance: 'Poisoning control guidance started',
    cardTitle: 'Poison Protocol',
    cardSub: 'Toxic substance response',
    cards: const [
      EmergencyActionCard(icon: '📞', label: 'Call Control', borderColor: Color.fromRGBO(229, 57, 53, 0.3), bgColor: Color.fromRGBO(229, 57, 53, 0.15)),
      EmergencyActionCard(icon: '🚫', label: 'No Vomiting', borderColor: Color.fromRGBO(183, 28, 28, 0.3), bgColor: Color.fromRGBO(183, 28, 28, 0.15)),
      EmergencyActionCard(icon: '📦', label: 'Check Label', borderColor: Color.fromRGBO(21, 101, 192, 0.3), bgColor: Color.fromRGBO(21, 101, 192, 0.15)),
      EmergencyActionCard(icon: '😮‍💨', label: 'Stay Calm', borderColor: Color.fromRGBO(46, 125, 50, 0.3), bgColor: Color.fromRGBO(46, 125, 50, 0.15)),
    ],
    voiceSteps: const [
      'What did they swallow? Find the bottle.',
      'Do not make them throw up.',
      'Call poison control immediately.',
      'Check if they are conscious.',
      'If they stop breathing, start CPR.',
      'Keep the substance container ready for the doctor.'
    ],
  ),
  'minor_ailment': EmergencyProtocol(

    id: 'minor_ailment',
    icon: '🩹',
    title: 'Minor Ailment',
    color: const Color.fromRGBO(46, 125, 50, 0.15),
    callLabel: 'Contact Doctor',
    panicLabel: '● Minor issue detected',
    initialMsg: 'Victim has a minor headache',
    responses: const [
      EmergencyResponse(text: '🩹 This looks like a minor ailment — I\'ll guide you through basic first aid', styleClass: 'suc'),
      EmergencyResponse(text: '💧 Drink some water and stay hydrated', styleClass: 'inf'),
      EmergencyResponse(text: '🛌 Rest in a quiet, dark room if possible', styleClass: 'inf'),
      EmergencyResponse(text: '💊 Consider a mild painkiller like paracetamol if safe for you', styleClass: 'inf'),
    ],
    timelineDesc: 'Minor ailment — symptoms reported',
    timelineGuidance: 'Basic first-aid guidance started',
    cardTitle: 'Care Protocol',
    cardSub: 'Basic first-aid',
    cards: const [
      EmergencyActionCard(icon: '💧', label: 'Hydrate', borderColor: Color.fromRGBO(46, 125, 50, 0.3), bgColor: Color.fromRGBO(46, 125, 50, 0.15)),
      EmergencyActionCard(icon: '🛌', label: 'Rest', borderColor: Color.fromRGBO(21, 101, 192, 0.3), bgColor: Color.fromRGBO(21, 101, 192, 0.15)),
      EmergencyActionCard(icon: '💊', label: 'Medication', borderColor: Color.fromRGBO(255, 143, 0, 0.3), bgColor: Color.fromRGBO(255, 143, 0, 0.15)),
      EmergencyActionCard(icon: '😮‍', label: 'Stay Calm', borderColor: Color.fromRGBO(121, 85, 72, 0.3), bgColor: Color.fromRGBO(121, 85, 72, 0.15)),
    ],
    voiceSteps: const [
      'Take a deep breath. You are safe.',
      'Drink a glass of water slowly.',
      'If your head hurts, find a quiet place to sit.',
      'Check if you have any other symptoms.',
      'If the pain gets worse, contact a professional.',
      'I am here to help you feel better.'
    ],
  ),
  'custom': EmergencyProtocol(

    id: 'custom',
    icon: '🚨',
    title: 'Emergency',
    color: const Color.fromRGBO(229, 57, 53, 0.15),
    callLabel: 'Call Emergency Services',
    panicLabel: '● Emergency detected',
    initialMsg: '',
    responses: const [
      EmergencyResponse(text: 'I\'m here. Describe what happened and I\'ll guide you.', styleClass: ''),
    ],
    timelineDesc: 'Emergency reported',
    timelineGuidance: 'Guidance started',
    cardTitle: 'Take Action',
    cardSub: 'Emergency protocol',
    cards: const [
      EmergencyActionCard(icon: '😮‍💨', label: 'Stay Calm', borderColor: Color.fromRGBO(21, 101, 192, 0.3), bgColor: Color.fromRGBO(21, 101, 192, 0.15)),
      EmergencyActionCard(icon: '📞', label: 'Call 112', borderColor: Color.fromRGBO(229, 57, 53, 0.3), bgColor: Color.fromRGBO(229, 57, 53, 0.15)),
      EmergencyActionCard(icon: '📍', label: 'Share Location', borderColor: Color.fromRGBO(255, 143, 0, 0.3), bgColor: Color.fromRGBO(255, 143, 0, 0.15)),
      EmergencyActionCard(icon: '🙋', label: 'Get Help', borderColor: Color.fromRGBO(46, 125, 50, 0.3), bgColor: Color.fromRGBO(46, 125, 50, 0.15)),
    ],
    voiceSteps: const [
      'Stay calm. Tell me exactly what happened.',
      'Is anyone injured? Check now.',
      'Move to a safe location if possible.',
      'Help is being contacted. Stay on the line.',
      'I will guide you through every step.',
      'You are not alone. Keep talking to me.'
    ],
  ),
};
